version: '3'

services:
  db:
    image: postgres:alpine
    container_name: project_db
    volumes:
      - project-db:/var/lib/postgresql/data
  web:
    restart: always
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DEBUG: 'true'
    depends_on:
      - db
volumes:
  project-db: